image: node:12.3.1

before_script:
- yarn

cache:
  paths:
  - node_modules/

stages:
  - eslint
  - unittest

CodeLint:
  stage: eslint
  script:
    - yarn lint
  except:
    - /^test-.*$/

UnitTest:
  stage: unittest
  script:
    - yarn test
  only:
    - master
