image: node:12.3.1

before_script:
  - npm i

stages:
  - eslint
  - unittest

CodeLint:
  stage: eslint
  script:
  - npm run lint

UnitTest:
  stage: unittest
  script:
    - npm run test
  only:
    - master